---
- name: Issue POST call
  hosts: localhost
  tasks:
    - name: Send POST request
      uri:
        url: "http://10.66.69.184:8000/automate"
        method: POST
        body_format: json
        body:
          value: 2
      register: result

    - name: Display response
      debug:
        var: result
